# Generated by Django 5.1.6 on 2025-02-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_leilao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leiloeiro',
            old_name='matricula',
            new_name='numero_matricula',
        ),
    ]
