# Generated by Django 5.1.6 on 2025-02-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_leilao', '0002_rename_matricula_leiloeiro_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leiloeiro',
            name='numero_matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_leilao.matricula'),
        ),
    ]
